name: build

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - 'master'
  schedule:
    - cron: '17 8 * * 0'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip'
        cache-dependency-path: |
          requirements.txt
          requirements-dev.txt
    - run: pip install -r requirements-dev.txt
    - run: python3 -m pytest --junitxml=test-report.xml
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Test Results
        path: |
          test-report.xml

  docker:
    runs-on: ubuntu-latest

    env:
      REGISTRY: ghcr.io
      IMAGENAME: ghcr.io/${{ github.repository }}/zpf-backstage-tv

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ${{ env.IMAGENAME }}
        # generate Docker tags based on the following events/attributes
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=sha

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Determine version string
      run: echo "VERSION=$(git describe --always --match --tags 'v*' --dirty)" >> $GITHUB_ENV

    - name: Build and push Docker images
      uses: docker/build-push-action@v6
      with:
        context: .
        build-args: |
          VERSION=${{ env.VERSION }}
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=registry,ref=${{ env.IMAGENAME }}:buildcache
        cache-to: type=registry,ref=${{ env.IMAGENAME }}:buildcache,mode=max

  # needed by test results workflow
  event_file:
    name: "Event File"
    runs-on: ubuntu-latest
    steps:
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: Event File
        path: ${{ github.event_path }}
